security:
    encoders:
        CAIF\SharedBundle\Entity\Person:
            algorithm: bcrypt

    providers:
        chain_provider:
            chain:
                providers: [admin, host, student]
        admin:
            id: caif_shared.admin_user_provider
        host:
            id: caif_shared.host_user_provider
        student:
            id: caif_shared.student_user_provider
        # administrators:
        #     entity: { class: CAIFSharedBundle:Person }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        demo_secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _demo_security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo

        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: caif_shared_login_target
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgot, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgotPassword$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/manage, roles: ROLE_ADMIN }
